import openai
import gradio
from pptx import Presentation
from pptx.util import Inches

openai.api_key = "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"

# create a new PowerPoint presentation
prs = Presentation()

# add the title slide
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
title.text = "Conversation History"
subtitle.text = "Generated by Real Estate Pro"

messages = [{"role": "system", "content": "You are a financial experts that specializes in real estate investment and negotiation"}]

def CustomChatGPT(user_input):
    messages.append({"role": "user", "content": user_input})
    response = openai.ChatCompletion.create(
        model = "gpt-3.5-turbo",
        messages = messages
    )
    ChatGPT_reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": ChatGPT_reply})

    # add a new slide for the current user input and Real Estate Pro response
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    shapes = slide.shapes
    shapes.title.text = "User: " + user_input
    body_shape = shapes.placeholders[1]
    tf = body_shape.text_frame
    tf.text = "Real Estate Pro: " + ChatGPT_reply
    tf.fit_text(font_family='Calibri', max_size=18)

    return ChatGPT_reply

demo = gradio.Interface(fn=CustomChatGPT, inputs="text", outputs="text", title="Real Estate Pro")
demo.launch(share=True)

# save the PowerPoint presentation

prs.save("conversation_history.pptx")
